/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code401challenges;

public class ArrayShift{
    public static int[] insertShiftArray(int[] arr, int value) {


        int n = arr.length;
        int[] arr1 = new int[n + 1];


        int half = arr.length / 2 + 1;
        for (int i = 0; i < arr1.length; i++) {
            if (i < half) {
                arr1[i] = arr[i];
            } else if (i == half) {
                arr1[i] = value;
            } else {
                arr1[i] = arr[i - 1];
            }
        }
//        for (int j = 0; j < arr1.length; j++) {
//            System.out.println(arr1[j]);
//        }
        return arr1;


    }


}
