/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java.data.structures.and.algorithms;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
