/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code401challenges;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {

        int[] input = new int[]{1,2,3,4,5};
        int value = 9;
        int[] expected = new int[]{1,2,3,9,4,5};
        assertArrayEquals("inserted value into middle of array", expected, ArrayShift.insertShiftArray(input, value));
    }


}
